# Generated by Django 3.2 on 2021-04-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
