# Generated by Django 3.2 on 2021-04-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_api_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='sid',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
