# Generated by Django 3.2 on 2021-04-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_api_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
